main:
  - pageRef: "/"
    name: "Home"
    url: "/"
    weight: 10
  - pageRef: "/post"
    name: "Blog"
    url: "/post"
    weight: 20
  - pageRef: "/micro"
    name: "Micro"
    url: "/micro"
    weight: 22
  - pageRef: "/photos"
    name: "Photos"
    url: "/photos"
    weight: 25
  - pageRef: "/series"
    name: "Series"
    url: "/series"
    weight: 27
  - pageRef: "/now"
    name: "Now"
    url: "/now"
    weight: 28
  - pageRef: "/slashpages"
    name: "SlashPages"
    url: "/slashpages"
    weight: 30
