main:
  - pageRef: "/"
    name: "Home"
    url: "/"
    weight: 10
  - pageRef: "/post"
    name: "Blog"
    url: "/post"
    weight: 20
  - pageRef: "/micro"
    name: "Micro"
    url: "/micro"
    weight: 22
  - pageRef: "/photos"
    name: "Photos"
    url: "/photos"
    weight: 25
  - pageRef: "/feeds"
    name: "Feeds"
    url: "/feeds"
    weight: 30
  - pageRef: "/now"
    name: "Now"
    url: "/now"
    weight: 40
  - pageRef: "/uses"
    name: "Uses"
    url: "/uses"
    weight: 50
