main:
  - pageRef: "/"
    name: "Home"
    url: "/"
    weight: 10
  - pageRef: "/post"
    name: "Blog"
    url: "/post"
    weight: 20
  - pageRef: "/micro"
    name: "Micro"
    url: "/micro"
    weight: 22
  - pageRef: "/photos"
    name: "Photos"
    url: "/photos"
    weight: 25
  - pageRef: "/explore"
    name: "Explore"
    url: "/explore"
    weight: 30
