subtitle: import antigravity
title: Fundor 333
description: Fundor 333's personal space on the web
favicon: /img/favicon.ico
image: /img/pilogo.jpg
logo: /img/pilogo.jpg
hostName: "https://fundor333.com"
copyright: Fundor333
