subtitle: Verified (12€/year for the domain)
title: Fundor 333
description: Fundor 333's personal space on the web
favicon: /img/favicon.ico
image: /img/pilogo.jpg
logo: /img/logo.jpg
hostName: "https://fundor333.com"
copyright: Fundor333
