title: Fundor 333
subtitle: Verified (12€/year for the domain)
description: Fundor 333's personal space on the web
image: /img/pilogo.jpg
logo: /img/logo.png
hostName: "https://fundor333.com"
copyright: Fundor333
photoLicense: CC BY-NC-ND 4.0

maciaindieweb:
  webmention: "https://micro.blog/webmention"
  pingback: "https://webmention.io/fundor333.com/xmlrpc"
  micropub: "https://micro.blog/micropub"
  microsub: "https://micro.blog/microsub"
  authorization_endpoint: "https://micro.blog/indieauth/auth"
  token_endpoint: "https://micro.blog/indieauth/token"
  subscribe: "https://micro.blog/users/follow"

  auth:
    twitter: https://twitter.com/fundor333
    mastodon: https://mastodon.social/@fundor333

author:
  name: Fundor 333
  email: "blog@fundor333.com"
  twitterpage: "https://twitter.com/fundor333"
  avatar: "/img/gatto.jpg"
  url: "https://fundor333.com/cv/"
  authorURL: "https://fundor333.com/"
  description: "Pythonista, Backend Developer, Dev Ops, Ex-Scout, Bookworm and Tea Lover. Sometime you can find me in a GDG, a DataBeers, a Pycon or other similar event. Huge Open Source fan and user I am allways searching something new to do or to study. Huge fan of automation, autodeploy and bots. A lot of my personal stuff are on my blog and more in my Github"
  fediverse: "@fundor333@micro.blog"
