subtitle: Verified (12€/year for the domain)
title: Fundor 333
description: Fundor 333's personal space on the web
favicon: /img/favicon.ico
image: /img/pilogo.jpg
logo: /img/logo.jpg
hostName: "https://fundor333.com"
copyright: Fundor333

maciaindieweb:
  webmention: "https://webmention.io/fundor333.com/webmention"
  pingback: "https://webmention.io/fundor333.com/xmlrpc"
  micropub: "https://appletune.fundor333.com/micropub"
  microsub: "https://aperture.p3k.io/microsub/699"
  authorization_endpoint: "https://indieauth.com/auth"
  token_endpoint: "https://tokens.indieauth.com/token"

  auth:
    twitter: https://twitter.com/fundor333
    mastodon: https://mastodon.social/@fundor333
