[tool.poetry]
name = "fundor333-github-io"
version = "0.1.0"
description = ""
authors = ["Fundor333 <fundor333@fundor333.com>"]
readme = "README.md"
packages = [{include = "fundor333"}]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
feedparser = "^6.0.11"
rich = "^13.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
