name: Cron Anilist

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  Anilist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master

      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: uv sync

      - name: Run Anylist
        run: uv run python ./action_script/aniist_run.py
