name: Cron Webmentions

on:
  schedule:
    - cron: "0 */10 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  webmentions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: uv sync

      - name: Fetch Syndication
        run: uv run python -m syndication_cli all-cmd

      - name: Fetch webmentions
        env:
          WEBMENTIONS_TOKEN: ${{ secrets.WEBMENTIONS_TOKEN }}
        run: uv run python ./action_script/webmention.py

      - name: Commit to repository
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          COMMIT_MSG: |
            👾Fetch webmentions
            skip-checks: true
        run: |
          git config user.email "git@fundor333.com"
          git config user.name "fundor333"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/fundor333/fundor333.github.io.git
          git checkout main
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin main)
